name: flutter_clone_shopee
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  get: 4.3.8
  material_design_icons_flutter: ^5.0.6295
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
